#!/usr/bin/env python3
"""Assembles the operator-journey document from the artifacts actually produced.

Everything embedded here was generated by the run in this directory: the CLI
blocks are transcript.sh's real stdout+stderr, the plate images are
`me bundle --preview`'s output, and the screenshots are frames the emulator
canvas handed back over HTTP. Nothing is drawn or paraphrased.
"""

import base64
import html
import json
import os
import re
import shutil
import subprocess
import sys

# ── Missing-asset gate (P1, 2026-08-19) ────────────────────────────────────
# `img()` renders a "missing:" placeholder when a screenshot is absent, and the
# build used to carry on and exit 0. Measured by the constellation recon: BOTH
# wallet journeys were building with 100 % of their referenced screenshots
# missing and still reporting success -- a document that silently asserts less
# than it claims, which is the failure the journeys README is itself about.
#
# A skipped step must FAIL, not pass. Enforcement is the DEFAULT and needs no
# flag to switch on; `--allow-missing` is the explicit opt-OUT for a deliberate
# draft build. Never the reverse -- a gate that an env var or flag has to ENABLE
# is a gate that is off whenever someone forgets it.
#
# (Duplicated verbatim in the three build_pdf*.py scripts, which already carry
# their own copies of img(). Keep them identical.)
MISSING = []
ALLOW_MISSING = "--allow-missing" in sys.argv


def missing_gate(artifact):
    """Exit non-zero if any referenced asset was absent. Call last."""
    if not MISSING:
        return
    uniq = sorted(set(MISSING))
    print(
        f"\n{len(MISSING)} missing asset(s), {len(uniq)} distinct -- "
        f"{artifact} is INCOMPLETE:",
        file=sys.stderr,
    )
    for name in uniq:
        print(f"  missing: {name}", file=sys.stderr)
    if ALLOW_MISSING:
        print("--allow-missing given: exiting 0 with an incomplete document.",
              file=sys.stderr)
        return
    print("Refusing to report success. Capture the screenshots (see "
          "README.md 'Reproducing'), or pass --allow-missing for a draft.",
          file=sys.stderr)
    sys.exit(1)


W = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(W, "out")
SHOTS = os.path.join(W, "shots")

# CAPTURED DATA, NOT PROSE (F-210). capture_operator.py writes both files; the
# captions are what the plate overlay itself rendered at each sample, and the
# carousel list is what the walk actually stepped through.
CAPTIONS, CAROUSEL = {}, {}
_cap = os.path.join(SHOTS, "captions-operator.json")
if os.path.exists(_cap):
    for _c in json.load(open(_cap)):
        CAPTIONS[_c["name"]] = _c
_car = os.path.join(SHOTS, "carousel-operator.json")
if os.path.exists(_car):
    CAROUSEL = json.load(open(_car))


def plate_caption(name):
    """The caption for one plate shot, or a refusal to invent one."""
    c = CAPTIONS.get(name)
    if not c:
        MISSING.append(name + " (caption)")
        return "no caption captured for this plate"
    m = re.search(r"head\s*([\d.]+),\s*([\d.]+)mm", c["caption"])
    head = f"head {m.group(1)}, {m.group(2)} mm" if m else c["caption"]
    pct = c.get("percent", "?")
    if pct == 100:
        return f"complete — {head}"
    return f"{head} — {pct}% of the cut"


def carousel_entries():
    """The program names the walk read off the carousel, spaced for prose."""
    got = CAROUSEL.get("entries") or []
    if not got:
        MISSING.append("carousel-operator.json")
        return [], "the carousel was not captured"
    # The walk squashes whitespace out of the screen text, so put the spaces
    # back before each capital that follows a letter OR A DIGIT: "BackupWallet"
    # -> "Backup Wallet", and "BIP-39Password" -> "BIP-39 Password", which the
    # letter-only rule left joined. A hyphen is not a word break here, so
    # "Engrave Single-Sig" survives intact.
    pretty = [re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", g) for g in got]
    return pretty, " · ".join(pretty)


def b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def img(path, cls="", cap=None, crop=None):
    if not os.path.exists(path):
        MISSING.append(os.path.basename(path))
        return f'<p class="missing">missing: {html.escape(os.path.basename(path))}</p>'
    src = path
    if crop:
        # The plate is square but the engraving occupies only its top band;
        # showing the empty two-thirds just shrinks the part worth reading.
        from PIL import Image
        im = Image.open(path)
        src = path.replace(".png", "-crop.png")
        im.crop((0, 0, im.width, int(im.height * crop))).save(src)
    tag = f'<img class="{cls}" src="data:image/png;base64,{b64(src)}">'
    if cap:
        return f'<figure>{tag}<figcaption>{cap}</figcaption></figure>'
    return tag


def code(text, limit=None):
    lines = text.rstrip("\n").split("\n")
    clipped = False
    if limit and len(lines) > limit:
        lines = lines[:limit]
        clipped = True
    body = html.escape("\n".join(lines))
    if clipped:
        body += "\n<span class='clip'>… clipped in this document; full text in out/transcript.txt</span>"
    return f"<pre>{body}</pre>"


def filebox(path, label=None, limit=None):
    name = label or os.path.relpath(path, W)
    with open(path) as f:
        return f'<div class="file"><div class="fname">{html.escape(name)}</div>{code(f.read(), limit)}</div>'


# ---------------------------------------------------------------- transcript --
# F-210 class, third instance: this used to read out/transcript.txt, an
# intermediate NO committed script writes — it existed only because an earlier
# session had left it there by manual redirect. The tracked artifact is the
# transcript at the journeys root, so read that.
with open(os.path.join(W, "transcript.txt")) as f:
    transcript = f.read()

sections = {}
cur, buf = None, []
for line in transcript.split("\n"):
    m = re.match(r"^########## (.*)$", line)
    if m:
        if cur:
            sections[cur] = "\n".join(buf).strip("\n")
        cur, buf = m.group(1), []
    else:
        buf.append(line)
if cur:
    sections[cur] = "\n".join(buf).strip("\n")

# F-210 class: keys.json was NEVER COMMITTED, so this script could not run at
# all — the same defect the pathological builder already worked around. Nothing
# here needs a vanished artifact: the fingerprints are in the committed key
# files' header comments, and the mk1 chunk pairs come from the bundle THIS RUN
# built (out/backup-strings.txt), so the captions are traceable to the journey
# rather than to a file somebody once had.
def _keys_from_run():
    d = os.path.join(W, "inputs", "keys")
    bundle = os.path.join(OUT, "backup-strings.txt")
    if not os.path.exists(bundle):
        raise SystemExit(f"{bundle} missing — run transcript.sh first; it builds the bundle")
    mk1 = [l for l in open(bundle).read().split("\n") if l.startswith("mk1")]
    out = []
    for i, f in enumerate(sorted(os.listdir(d))):
        m = re.search(r"\[([0-9a-f]{8})/([^\]]+)\]", open(os.path.join(d, f)).read())
        if not m:
            raise SystemExit(f"{f}: no [fingerprint/path] header -- cannot caption its plates")
        pair = mk1[i * 2:i * 2 + 2]
        if len(pair) != 2:
            raise SystemExit(f"{f}: expected 2 mk1 chunks at offset {i*2}, got {len(pair)}")
        out.append({"index": i, "fingerprint": m.group(1), "mk1_raw": pair})

    # I-3: this document mixes a COMMITTED transcript with a LIVE bundle. If
    # out/ is from a different run than transcript.txt, the page renders one
    # card string in its transcript blocks and a different one in its tables —
    # for the SAME key — and nothing complains. Refuse that rather than publish
    # it: every card in the bundle must appear in the transcript being quoted.
    # Direction matters: the transcript only QUOTES the first card (it runs
    # `mk inspect` on one pair), so requiring every bundle card to appear in it
    # is wrong — that was this guard's first, over-strict form, and it fired on
    # a perfectly consistent pair of artifacts. The real invariant is the other
    # way round: every mk1 string the transcript SHOWS must be one the bundle
    # actually contains. A transcript from an older run quotes strings that are
    # not in today's bundle, and that is exactly the mixed document I-3 found.
    tr = open(os.path.join(W, "transcript.txt")).read()
    in_bundle = {c for k in out for c in k["mk1_raw"]}
    quoted = set(re.findall(r"\bmk1[0-9a-z]+", tr))
    orphan = sorted(q for q in quoted if q not in in_bundle)
    if orphan:
        raise SystemExit(
            "transcript.txt quotes mk1 strings that are NOT in "
            "out/backup-strings.txt — the two are from different runs.\n"
            f"  first orphan: {orphan[0]}\n"
            "  Re-run transcript.sh, refresh transcript.txt, then rebuild.")
    return out


keys = _keys_from_run()

# The plate checklist, lifted from the bundle run.
checklist = ""
m = re.search(r"me: backup needs .*?(?=\n\[exit)", transcript, re.S)
if m:
    checklist = m.group(0)

CSS = """
:root { --ink:#16181d; --dim:#5b6270; --line:#d7dbe2; --accent:#1a5fb4; --warn:#b3261e; }
* { box-sizing: border-box; }
body { font: 10.5px/1.5 -apple-system,'Segoe UI',Roboto,sans-serif; color: var(--ink);
       margin: 0; padding: 0; }
h1 { font-size: 25px; margin: 0 0 4px; letter-spacing:-.4px; }
h2 { font-size: 15px; margin: 0 0 10px; padding-bottom: 5px;
     border-bottom: 2px solid var(--accent); color: var(--accent); }
h3 { font-size: 11.5px; margin: 14px 0 6px; color: var(--dim);
     text-transform: uppercase; letter-spacing: .7px; }
p { margin: 0 0 8px; }
.page { padding: 15mm 14mm; page-break-after: always; }
.page:last-child { page-break-after: auto; }
.sub { color: var(--dim); font-size: 11px; margin-bottom: 14px; }
pre { font: 8.2px/1.38 'DejaVu Sans Mono',Menlo,monospace; background:#f6f7f9;
      border:1px solid var(--line); border-left:3px solid var(--accent);
      padding:7px 9px; margin:0; white-space: pre-wrap; word-break: break-all;
      border-radius:2px; }
.file { margin-bottom: 9px; }
.fname { font: 700 8.6px 'DejaVu Sans Mono',monospace; color:#fff;
         background: var(--dim); display:inline-block; padding:2px 7px;
         border-radius:2px 2px 0 0; }
.file pre { border-radius: 0 2px 2px 2px; }
.clip { color: var(--dim); font-style: italic; }
.missing { color: var(--warn); font-style: italic; }
figure { margin: 0; }
figcaption { font-size: 8.2px; color: var(--dim); margin-top: 3px; line-height:1.35; }
.grid2 { display:grid; grid-template-columns:1fr 1fr; gap:10px; }
.grid3 { display:grid; grid-template-columns:repeat(3,1fr); gap:9px; }
.grid4 { display:grid; grid-template-columns:repeat(4,1fr); gap:7px; }
.screen { width:100%; border:1px solid var(--line); border-radius:3px; display:block; }
.plate { width:100%; border:1px solid var(--line); border-radius:3px; display:block;
         background:#fff; }
.note { background:#fff8e1; border:1px solid #e8c962; border-left:3px solid #d39e00;
        padding:8px 10px; margin:9px 0; border-radius:2px; }
.warn { background:#fdecea; border:1px solid #f0b3ae; border-left:3px solid var(--warn);
        padding:8px 10px; margin:9px 0; border-radius:2px; }
/* Only the LEAD bold is a heading; bolds inside the prose must stay inline or
   they break sentences onto their own lines. */
.warn > b:first-child, .note > b:first-child { display:block; margin-bottom:2px; }
table { border-collapse:collapse; width:100%; font-size:8.4px; }
th,td { border:1px solid var(--line); padding:3px 5px; text-align:left;
        vertical-align:top; }
th { background:#eef1f5; font-weight:700; }
td.mono, th.mono { font-family:'DejaVu Sans Mono',monospace; word-break:break-all; }
.kv { font-size:9.4px; }
.kv td:first-child { color:var(--dim); width:34%; }
.foot { color:var(--dim); font-size:8px; border-top:1px solid var(--line);
        padding-top:5px; margin-top:12px; }
"""

parts = []

# ------------------------------------------------------------------- cover --
parts.append(f"""
<div class="page">
<h1>SeedHammer II — operator journey</h1>
<div class="sub">Backing up a 5-of-12 multisig from files, end to end:
constellation CLIs on the host, the firmware GUI in the emulator, and the
plates that come out.</div>

<div class="warn"><b>Test material only — never put funds behind these keys.</b>
Every seed in this document was derived deterministically from the public string
<code>"shibboleth journey cosigner &lt;i&gt;"</code> so the run reproduces exactly.
They are public by construction.</div>

<h2>What this run actually was</h2>
<p>The <em>pathological</em> wallet from the constellation corpus:
<code>wsh(multi(5, @0…@11))</code> — twelve cosigners, five signatures.</p>

<div class="note"><b>One correction, measured rather than assumed.</b>
<code>CORPUS.md</code> calls its own C6 "pathological deeply-nested miniscript"
entry <em>a placeholder</em>, noting the 8-nested-<code>or_d</code> form
"actually fits single string (45 B)". The 12-key <code>multi(5,…)</code> policy
used here comes instead from <code>phase-6-bucket-C.md</code>, which calls it
"reliably &gt;56 bytes bytecode" — no longer true of today's encoder.
<code>md bytecode</code> reports <b>13 bytes</b>, and it encodes to a
<b>single</b> md1 string: a keyless BIP-388 template does not pay per key. The
chunking in this run comes from the <b>mk1 key cards</b>, which do carry xpubs —
every one of the twelve splits in two.</div>

<h2>Toolchain, as reported by the binaries</h2>
{code(sections.get('versions',''))}

<h2>The shape of the job</h2>
<table class="kv">
<tr><td>Policy</td><td><code>wsh(multi(5,@0/&lt;0;1&gt;/*,…,@11/&lt;0;1&gt;/*))</code></td></tr>
<tr><td>Cosigners</td><td>12, each at <code>m/48'/0'/0'/2'</code>, mainnet</td></tr>
<tr><td>md1 descriptor strings</td><td>1 (13-byte bytecode)</td></tr>
<tr><td>mk1 key-card strings</td><td>24 (12 keys × 2 chunks)</td></tr>
<tr><td>Public plates</td><td>25</td></tr>
<tr><td>Secret plates</td><td>1 (ms1 — typed on the machine, never over the wire)</td></tr>
<tr><td><b>Total plates</b></td><td><b>26</b></td></tr>
</table>
<p style="margin-top:6px">Twenty-six plates is the honest cost of a 5-of-12 held
this way, and it is the number the operator most needs before starting.</p>
</div>
""")

# -------------------------------------------------------------- input files --
seed_files = sorted(os.listdir(os.path.join(W, "inputs", "seeds")))
key_files = sorted(os.listdir(os.path.join(W, "inputs", "keys")))

parts.append(f"""
<div class="page">
<h2>The input files</h2>
<p>Everything the operator supplies lives on disk before a single command runs.
Contents below are complete and unedited.</p>

<h3>The wallet policy</h3>
{filebox(os.path.join(W,'inputs','wallet-policy.txt'), 'inputs/wallet-policy.txt')}

<h3>The twelve seeds (SECRET — test material)</h3>
<div class="grid2">
{''.join(filebox(os.path.join(W,'inputs','seeds',f), 'inputs/seeds/'+f) for f in seed_files)}
</div>
</div>

<div class="page">
<h2>The input files, continued</h2>
<h3>The twelve cosigner keys</h3>
<div class="grid2">
{''.join(filebox(os.path.join(W,'inputs','keys',f), 'inputs/keys/'+f) for f in key_files)}
</div>
</div>
""")

# ------------------------------------------------------------ derived cards --
rows = "".join(
    f"<tr><td>{k['index']}</td><td class='mono'>{k['fingerprint']}</td>"
    f"<td class='mono'>{html.escape(k['mk1_raw'][0][:44])}…</td>"
    f"<td class='mono'>{html.escape(k['mk1_raw'][1][:44])}…</td></tr>"
    for k in keys)

parts.append(f"""
<div class="page">
<h2>Host step 1 — the descriptor</h2>
{code(sections.get('1. the wallet policy, from file',''), 46)}
</div>

<div class="page">
<h2>Host step 2 — a key card</h2>
<p>One cosigner shown in full; the other eleven are identical in form.</p>
{code(sections.get('2. one cosigner key, from file',''), 44)}

<h3>All twelve, as encoded</h3>
<table>
<tr><th>#</th><th class="mono">fingerprint</th><th class="mono">mk1 chunk 1/2</th><th class="mono">mk1 chunk 2/2</th></tr>
{rows}
</table>
</div>

<div class="page">
<h2>Host step 3 — the seed, and the line the tool will not cross</h2>
{code(sections.get('3. one seed, from file (SECRET)',''), 22)}
<div class="warn"><b>ms1 is refused on the radio path, by design.</b>
Feeding the same seed's ms1 string to the NFC converter does not produce a tag:</div>
{code(sections.get('5b. and the refusal that matters: ms1 never leaves the machine',''))}
<p>The descriptor, being public, converts without complaint:</p>
{code(sections.get('5. NDEF for the descriptor card',''))}
</div>

<div class="page">
<h2>Host step 4 — validate the bundle, get the checklist</h2>
{code(sections.get('4. the bundle: validate + plate manifest + checklist','').split('me: rendered plate 2')[0] + '  … (plates 2–25 rendered) …')}
<h3>The plate checklist, verbatim</h3>
{code(checklist)}
</div>

<div class="page">
<h2>Host step 5 — a systemwide payload</h2>
<p>The public cards can also be handed to the machine as one flash payload at
<code>0x10D00000</code>. The digest is what the operator compares on screen.</p>
{code(sections.get('6. a systemwide payload carrying the public cards',''))}
</div>

<div class="page">
<h2>Host step 6 — the addresses, and where their origins came from</h2>
<p>Everything above proves the bytes survive the card format. This is the other
half: that they mean the wallet we intended. <b>Compare these against your
coordinator before engraving anything.</b></p>
{code(sections.get('7. the addresses — and where their origins had to come from',''))}

<p class="note"><b>The origins are not on the card.</b> This policy's
<code>wsh(...)</code> wrapper is <em>canonical</em>, so <code>md</code> never
demanded an explicit origin and none was given — and a keyless template records
none of its own. <code>md inspect</code> on the engraved card reports
<code>m</code> for all twelve slots, which is what the block below shows. So the
twelve derivation paths used above were read from the cosigner key
<em>files</em>, not recovered from the card: <b>an operator holding only these
plates would have twelve xpub slots and no idea where any of the keys
live.</b></p>
{code(sections.get('7b. what the ENGRAVED card says about those origins',''), 24)}
</div>
""")

# --------------------------------------------------------------- the plates --
plate_imgs = sorted(
    (f for f in os.listdir(os.path.join(OUT, "plates")) if f.endswith(".png")),
    key=lambda s: int(re.search(r"(\d+)", s).group(1)))

caps = {1: "plate 1 — md1 policy"}
cells = []
for f in plate_imgs:
    n = int(re.search(r"(\d+)", f).group(1))
    if n == 1:
        cap = "plate 1 — md1 policy"
    else:
        key_i = (n - 2) // 2
        chunk = (n - 2) % 2 + 1
        cap = f"plate {n} — key {key_i} [{keys[key_i]['fingerprint']}] chunk {chunk}/2"
    cells.append(img(os.path.join(OUT, "plates", f), "plate", cap))

parts.append(f"""
<div class="page">
<h2>The 25 public plates</h2>
<p>Rendered by the <code>me-preview</code> sidecar, which reuses upstream
SeedHammer curve math — this is the layout the machine will cut.</p>
<div class="grid3">{''.join(cells[:12])}</div>
</div>
<div class="page">
<h2>The 25 public plates, continued</h2>
<div class="grid3">{''.join(cells[12:])}</div>
<div class="note"><b>Plate 26 is not here, and cannot be.</b>
The seed plate is engraved from an ms1 string typed on the machine. No host tool
in this constellation will render, transmit or preview it.</div>
</div>
""")

# ------------------------------------------------------------ the emulator --
def shot(n, cap):
    return img(os.path.join(SHOTS, n), "screen", cap)

parts.append(f"""
<div class="page">
<h2>On the machine — finding the program</h2>
<p>The emulator runs the real firmware GUI compiled to wasm, driven only through
the touch input the machine itself has.</p>
<div class="grid3">
{shot('j00-boot.png',f'Boot: the program carousel, {len(carousel_entries()[0])} entries')}
{shot('menu-4.png','Engrave Bundle — takes md1 + mk1 cards')}
{shot('j06-bundle-enter.png','The gatherer, waiting for cards')}
{shot('j01-backup-enter.png','Backup Wallet: seed source first')}
{shot('j02-sel-mstring.png','M*1 STRING selected')}
{shot('j03-mstring-prompt.png','bech32 keyboard — I, O and B are absent')}
</div>
<div class="note"><b>The {len(carousel_entries()[0])} programs, read off the carousel:</b>
{carousel_entries()[1]}.</div>
</div>

<div class="page">
<h2>On the machine — composing a plate</h2>
<div class="grid3">
{shot('k01-engrave-text-enter.png','QR: the warning is that a photo of the plate is a copy of the text')}
{shot('k04-font.png','Font: font/sh is this program’s own; font/constant is the face every seed and descriptor plate uses')}
{shot('k06-size.png','Size: auto-fit takes the largest that holds')}
{shot('k08-typed.png','Text entry masks by default')}
{shot('k09-revealed.png','“show” reveals it')}
{shot('k13-after-footer.png','Confirm — and it says plainly that nothing here is checked')}
</div>
</div>

<div class="page">
<h2>On the machine — the engrave</h2>
<div class="grid3">
{shot('k14-engrave-start.png','Insert a blank plate; hold to start')}
{shot('p2-screen.png','Countdown while cutting')}
{shot('p17-settled.png','Completed')}
</div>

<h2 style="margin-top:16px">The plate overlay, live</h2>
<p>At the moment the engrave begins the emulator draws the <b>whole planned
layout in grey</b>, from the same <code>PlanEngraving</code> call the firmware
makes. What the driver has actually stepped is filled in <b>black</b>, decoded
from the real step stream — not from the plan. The red circle is the head.</p>
<div class="grid2">
{img(os.path.join(SHOTS,'p0-plate.png'),'plate',plate_caption('p0-plate.png'), 0.30)}
{img(os.path.join(SHOTS,'p2-plate.png'),'plate',plate_caption('p2-plate.png'), 0.30)}
{img(os.path.join(SHOTS,'p5-plate.png'),'plate',plate_caption('p5-plate.png'), 0.30)}
{img(os.path.join(SHOTS,'p11-plate.png'),'plate',plate_caption('p11-plate.png'), 0.30)}
</div>
<div class="note"><b>Why the last frame reads 0.0, 0.0.</b>
The job ends by homing, so plan and progress stay in one coordinate space. Before
F-121 was fixed the emulator did not home while the device did, and a resumed cut
drew its progress roughly 68 mm away from its own plan.</div>
</div>
""")

# ---------------------------------------------------------------- findings --
parts.append(f"""
<div class="page">
<h2>What this run turned up</h2>

<div class="warn"><b>1. The emulator freezes when an NFC tag is presented to a gathering flow.</b>
<code>bundleGatherFlow</code> samples <code>Platform.NFCReader()</code> once on
entry, so a tag must already be pending or no scanner goroutine starts at all —
that part is merely awkward. The defect is what happens when one <em>is</em>
pending: the emulator's source is one-shot, so after the single record is read
the reader sits at EOF, and the scan loop only sleeps on
<code>scanFailed</code>. On <code>io.EOF</code> it spins. Under Go/wasm, which is
cooperatively scheduled on the browser's single thread, a goroutine that never
blocks starves the event loop and the page stops responding — confirmed here:
after presenting a card, even navigating away from the tab timed out.
<br><br>The consequence is that the NFC path added for the systemwide-payloads
work — the one path spec §8.2 exists to make walkable — cannot currently be
walked in the emulator, and a 25-card bundle could not be delivered over it in
any case, since one flow entry can consume exactly one tag.</div>

<div class="note"><b>2. CORPUS.md's C6 is still a placeholder, and the 12-key
policy is no longer chunk-forcing.</b> Measured: 13 bytes of bytecode, one md1
string. Whatever the corpus wants C6 to demonstrate, this policy no longer
demonstrates it — though it remains an excellent <em>operator</em> stress case at
26 plates.</div>

<div class="note"><b>3. <code>me bundle --preview</code> requires an empty output
directory</b> and exits 2 otherwise. Correct behaviour — worth knowing before a
re-run.</div>

<h2 style="margin-top:16px">Reproducing this document</h2>
{code('''cd <this directory>
bash transcript.sh > transcript.txt 2>&1         # every CLI block
python3 build_pdf.py                              # this PDF

# the cosigner set (run inside the seedhammer flake)
go run ./cmd/journeykeys > keys.json''')}
<div class="foot">The emulator frames were captured by POSTing
<code>canvas.toDataURL()</code> to a local receiver, so each screenshot is the
device framebuffer exactly — no browser chrome, no scaling.</div>
</div>
""")

doc = f"<!doctype html><meta charset=utf-8><title>SeedHammer II operator journey</title><style>{CSS}</style>" + "".join(parts)
path = os.path.join(OUT, "journey.html")
with open(path, "w") as f:
    f.write(doc)
print(f"wrote {path} ({len(doc)//1024} KB)")

# GATED BEFORE THE PRINT. The PDF path is the committed deliverable, so printing
# first and checking second overwrites a good document with an incomplete
# rebuild and only then reports failure.
missing_gate(path)

# THE PDF STEP (the rest of F-156). This builder stopped at HTML and the
# published PDF came from a manual headless-Chrome pass that lived nowhere in
# the repo. Same three lines build_pdf_payload.py has always had.
PDF = os.path.join(W, "SeedHammer-II-operator-journey.pdf")
chrome = os.environ.get("CHROME") or shutil.which("chromium") or shutil.which("google-chrome")
if not chrome:
    guess = os.path.expanduser("~/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome")
    chrome = guess if os.path.exists(guess) else None
if not chrome:
    print("no chrome/chromium found; set $CHROME to one. HTML is written.", file=sys.stderr)
    sys.exit(1)
subprocess.run(
    [chrome, "--headless", "--disable-gpu", "--no-sandbox",
     "--no-pdf-header-footer", f"--print-to-pdf={PDF}", "file://" + path],
    check=True, capture_output=True,
)
print(f"wrote {PDF} ({os.path.getsize(PDF)//1024} KB)")

