#!/usr/bin/env python3
"""Gate the journey's PROSE tier table against the POLICY it claims to describe.

WHY THIS EXISTS. The four-tier table in the transcript's section 1 reads like the
source of the wallet. It is not. The arrow runs the other way:

    operator's English spec
      -> a policy string HAND-WRITTEN once (hashlock-vault cycle, f39958b)
      -> copied byte-for-byte into design/fixtures/…/tr.policy (5b15b18)
      -> `sed` path substitution -> inputs-rcw/policy-{tr,wsh}.txt
      -> and, separately, a PROSE DESCRIPTION of it typed into the transcript

So the table is downstream of the policy and nothing tied them together. It was
checked once, by hand, and found accurate — which is exactly the state every
other unverified claim in this repo was in before it turned out to be wrong.

A description that cannot drift is worth more than one that happens to be right,
so this asserts each tier against the real string, per wrapper.

    python3 check_tiers.py inputs-rcw/policy-tr.txt tr
    python3 check_tiers.py inputs-rcw/policy-wsh.txt wsh

    python3 check_tiers.py <policy> <tr|wsh> [--preimages DIR]

EXIT CODES ARE LOAD-BEARING and must stay distinct:
    0  the tier table matches the policy
    1  it does NOT match -- a real finding about the wallet
    2  the check could not be EVALUATED (missing preimages, bad args, unreadable
       policy). NOT a finding about the wallet.

A caller that treats "non-zero" as "the gate detected something" is testing the
wrong layer, and that already happened: transcript_rcw.sh's negative control fed
this gate a policy copied to a scratch directory with no sibling preimages/, got
a non-zero exit for a MISSING FILE, and reported the gate as working. The
control proved nothing and would have gone on proving nothing indefinitely.
Exit 2 exists so a control can demand exit 1 specifically.
"""
import hashlib
import pathlib
import re
import sys


def die_setup(msg):
    """Exit 2: could not evaluate. Never 1 -- 1 means the POLICY is wrong."""
    print(f"CANNOT EVALUATE: {msg}", file=sys.stderr)
    sys.exit(2)


def literals(policy_path, pre_dir=None):
    """The three hash literals, DERIVED from the committed passphrases.

    Not hard-coded. Since 2026-08-22 the policy commits to sha256(sha256(phrase))
    -- miniscript's sha256() fragment emits `OP_SIZE <32> OP_EQUALVERIFY`, so the
    witness preimage must be exactly 32 bytes and these passphrases are 34-40.
    Deriving here means this gate also checks the phrase -> preimage -> literal
    chain, and cannot drift from `derive-rcw-keys.sh` the way a constant would.
    """
    pre = pathlib.Path(pre_dir) if pre_dir else pathlib.Path(policy_path).parent / "preimages"
    out = []
    for i in range(3):
        txt, hx = pre / f"preimage-{i}.txt", pre / f"preimage-{i}.hex"
        for f in (txt, hx):
            if not f.exists():
                die_setup(f"{f} missing -- the policy predates the "
                          f"double-hash fix of 2026-08-22, its preimages were "
                          f"not regenerated by derive-rcw-keys.sh, or it lives "
                          f"outside inputs-rcw/ (then pass --preimages DIR)")
        phrase = txt.read_bytes()
        inner = hashlib.sha256(phrase).digest()
        hexf = hx.read_text().strip()
        if inner.hex() != hexf:
            die_setup(f"preimage-{i}.hex is not sha256(preimage-{i}.txt)")
        if len(inner) != 32:
            die_setup(f"preimage-{i} is {len(inner)} bytes, not 32")
        out.append(hashlib.sha256(inner).hexdigest())
    return out


def leaves(pol):
    """Return the four OUTERMOST `and_v(...)` groups — the spend branches.

    Works for BOTH shapes: `tr()`'s taptree `{a,{b,{c,d}}}` and `wsh()`'s
    `or_i(a,or_i(b,or_i(c,d)))`.

    Outermost matters and a regex cannot do it. Tier 2 is a NESTED and_v —
    `and_v(v:older(32768),and_v(v:sha256(H2),multi_a(2,...)))` — so a
    single-level pattern grabs the INNER group and reports the branch as
    missing its timelock. That is exactly the false FAIL this function was
    first written with, which is a fair warning about describing structure
    with patterns instead of balancing brackets.
    """
    spans = []
    for m in re.finditer(r"and_v\(", pol):
        i = m.end() - 1
        depth = 0
        for j in range(i, len(pol)):
            if pol[j] == "(":
                depth += 1
            elif pol[j] == ")":
                depth -= 1
                if depth == 0:
                    spans.append((m.start(), j + 1))
                    break
    # Keep only spans not contained in another — the outermost branches.
    outer = [(a, b) for (a, b) in spans
             if not any(x < a and b <= y for (x, y) in spans if (x, y) != (a, b))]
    outer.sort()
    return [pol[a:b] for a, b in outer]


def main():
    args = sys.argv[1:]
    pre_dir = None
    if "--preimages" in args:
        i = args.index("--preimages")
        if i + 1 >= len(args):
            die_setup("--preimages needs a directory")
        pre_dir = args[i + 1]
        del args[i:i + 2]
    if len(args) != 2 or args[1] not in ("tr", "wsh"):
        die_setup(f"usage: {sys.argv[0]} <policy-file> <tr|wsh> [--preimages DIR]")
    try:
        pol = open(args[0]).read().strip()
    except OSError as e:
        die_setup(f"cannot read {args[0]}: {e}")
    wrap = args[1]
    H1, H2, H3 = literals(args[0], pre_dir)
    # multi_a is tapscript-only; the wsh form carries plain multi. Asserting the
    # RIGHT one per wrapper is itself a check — a wsh policy containing multi_a
    # would not be a valid wallet, and a tr one containing multi would be a
    # different script.
    m = "multi_a" if wrap == "tr" else "multi"

    claims = [
        ("tier 1", "@0+@1+@2 and sha256(H1), NO timelock",
         lambda l: f"{m}(3," in l and H1 in l and "older(" not in l and "after(" not in l
         and all(f"@{i}/" in l for i in (0, 1, 2))),
        ("tier 2", "@3+@4 and sha256(H2) after older(32768) [relative]",
         lambda l: f"{m}(2," in l and H2 in l and "older(32768)" in l
         and all(f"@{i}/" in l for i in (3, 4))),
        ("tier 3", "@5 alone after after(1173520) [absolute]",
         lambda l: "after(1173520)" in l and "pk(@5/" in l
         and "sha256" not in l and "multi" not in l),
        ("tier 4", "@6 and sha256(H3) after after(1383520) [absolute]",
         lambda l: "after(1383520)" in l and H3 in l and "pk(@6/" in l),
    ]

    ls = leaves(pol)
    if len(ls) != 4:
        sys.exit(f"FAIL[{wrap}]: parsed {len(ls)} spend branches, expected 4")

    bad = []
    for (name, desc, pred), leaf in zip(claims, ls):
        if pred(leaf):
            print(f"  {wrap} {name}: OK   {desc}")
        else:
            print(f"  {wrap} {name}: FALSE {desc}")
            print(f"      branch as written: {leaf[:110]}")
            bad.append(name)

    # THIS ASSERTION IS INVERTED, deliberately. It used to require EXACTLY ONE
    # keyless branch -- that was the wallet's defining property. The operator
    # ruled on 2026-08-22: "keyless path is not reasonable." So it now requires
    # ZERO, and the gate guards against REGRESSION rather than against loss.
    #
    # It is worth keeping rather than deleting: a keyless branch makes stock
    # rust-miniscript refuse the tr form outright ("All spend paths must require
    # a signature") while silently ACCEPTING the wsh form, because
    # Descriptor::from_str only sanity-checks Tr. Two forms of one wallet would
    # disagree about their own validity, and only one of them would say so.
    keyless = [l for l in ls if "pk(" not in l and "multi" not in l]
    if keyless:
        print(f"  {wrap}: {len(keyless)} keyless branches, expected 0 (ruled out 2026-08-22)")
        bad.append("keyless-count")

    if bad:
        sys.exit(f"FAIL[{wrap}]: the transcript's tier table does not match the "
                 f"policy: {', '.join(bad)}")
    print(f"  {wrap}: tier table matches the policy, and every tier requires a signature")


if __name__ == "__main__":
    main()
