#!/usr/bin/env bash
# transcript_rcw.sh — the REASONABLY COMPLEX WALLET journey, both wrappings.
#
# Every command below runs for real and its stdout+stderr and exit code are
# printed. Nothing here is a value somebody typed into a document.
#
# Regenerate:  bash transcript_rcw.sh > transcript_rcw.txt
# Inputs come from derive-rcw-keys.sh, which is their only producer.
set -uo pipefail

W="$(cd "$(dirname "$0")" && pwd)"
C=/scratch/code/shibboleth
MS=$C/mnemonic-secret/target/release/ms
MD=$C/descriptor-mnemonic/target/debug/md
MK=$C/mnemonic-key/target/debug/mk
ME=$C/mnemonic-engrave/target/debug/me
IN="$W/inputs-rcw"
OUT="$W/out/rcw"

FATAL=0
run() { echo "\$ $*"; "$@" 2>&1; echo "[exit $?]"; echo; }
fatal() { printf 'FATAL: %s\n\n' "$1"; FATAL=1; }
runcap() {
  local out="$1" keep="$2"; shift 2
  echo "\$ $*"
  local sout serr rc
  sout="$(mktemp)"; serr="$(mktemp)"
  "$@" >"$sout" 2>"$serr"; rc=$?
  cat "$sout"; cat "$serr"
  if ! grep -E "$keep" "$sout" > "$out"; then
    rm -f "$out"
    printf 'runcap: CAPTURE FAILED -- no stdout line matched /%s/\n' "$keep"
    [ "$rc" -eq 0 ] && rc=1
  fi
  rm -f "$sout" "$serr"
  echo "[exit $rc]"; echo
  return 0
}

for t in "$MS" "$MD" "$MK" "$ME"; do
  [ -x "$t" ] || { echo "FATAL: missing $t -- build it first" >&2; exit 1; }
done
[ -d "$IN" ] || { echo "FATAL: no $IN -- run ./derive-rcw-keys.sh first" >&2; exit 1; }
mkdir -p "$OUT"

# THE STALENESS STAMP. A transcript is a snapshot; this records WHICH generator
# produced it, so the PDF builder can refuse a snapshot from a different version
# of this script rather than rendering stale output that still parses.
echo "# transcript-generator-sha256: $(sha256sum "$0" | cut -d" " -f1)"
echo

echo "=== 0. Versions ==="
echo
run "$MS" --version
run "$MD" --version
run "$MK" --version
run "$ME" --version

echo "=== 1. THE STARTING REPRESENTATION ==="
echo
cat <<'TXT'
The starting representation of "our reasonably complex wallet" is a BIP-388
WALLET POLICY TEMPLATE: a miniscript expression in which every key is a
PLACEHOLDER -- @0 through @5 -- followed by that slot's derivation path and a
<0;1> multipath suffix for the receive/change chains.

It is NOT a descriptor, NOT an address, and NOT a set of keys. It is the SHAPE
of the wallet with key-shaped holes in it, and everything below is produced
from it plus the six seeds. That distinction is the whole reason a keyless
template can be engraved separately from the keys that fill it.

The four tiers, in the order the policy states them:

  tier 1   @0 and @1 and @2 and sha256(H1)          -- at any time
  tier 2   @3 and @4 and sha256(H2)                 -- after older(32768), relative
  tier 3   @5 alone                                 -- after height 1173520, absolute
  tier 4   sha256(H3) alone                         -- after height 1383520, absolute

Tier 4 has NO KEY. Whoever learns H3's preimage can spend it alone once that
height passes, which is why every encode below carries --experimental and why
the preimages are as sensitive as the seeds.

Two wrappings, which are DIFFERENT WALLETS with different addresses:

  tr   taproot, NUMS internal key so there is no key-path spend; the four tiers
       are four separate taptree leaves. Keys at m/270028'/0'/8'/0'.
  wsh  segwit v0; the taptree FLATTENS into one script, so the tiers become an
       or_i chain and multi_a becomes multi. Keys at m/270028'/0'/9'/1'.
TXT
echo
echo "The two policies, as generated by derive-rcw-keys.sh:"
echo
run cat "$IN/policy-tr.txt"
run cat "$IN/policy-wsh.txt"

echo "=== 2. Six seeds, one per key ==="
echo
for i in 0 1 2 3 4 5; do
  printf 'key-%d: %s\n' "$i" "$(cat "$IN/seeds/key-$i.seed")"
done
echo
echo "TEST MATERIAL: entropy 0x000..001 through 0x000..006. Never put funds behind these."
echo

echo "=== 3. The seed fingerprint of each seed ==="
echo
# The master fingerprint is a property of the SEED, not of any derivation path,
# so it is the same in both wrappings. Asserted rather than asserted-in-prose.
echo "  key   fingerprint"
for i in 0 1 2 3 4 5; do
  printf '  @%d    %s\n' "$i" "$(cat "$IN/seeds/key-$i.fingerprint")"
done
echo
NFP=$(cat "$IN"/seeds/key-*.fingerprint | sort -u | wc -l)
echo "$NFP distinct fingerprints across 6 seeds."
[ "$NFP" -eq 6 ] || fatal "expected 6 distinct seed fingerprints, got $NFP"
echo

echo "=== 4. The keys, at the bg002h path ==="
echo
cat <<'TXT'
bg002h is m/270028'/coin'/account'/script', with the level-4 script value ruled
0' = tr and 1' = wsh. The operator selected ACCOUNT 8 for the tr form and
ACCOUNT 9 for the wsh form, so the two wallets hold disjoint keys derived from
the same six masters.
TXT
echo
for w in tr wsh; do
  echo "-- $w --"
  run head -3 "$IN/keys-$w/key-0.xpub"
done

# ── Everything per-wrapper, in one loop so the two cannot drift ──────────────
for w in tr wsh; do
  POL="$IN/policy-$w.txt"
  O="$OUT/$w"
  mkdir -p "$O"
  P=$(cat "$POL")

  # Per-slot key and fingerprint arguments, read from the key files themselves.
  KEYARGS=(); FPARGS=(); KEYFILE="$O/keys.txt"; : > "$KEYFILE"
  for i in 0 1 2 3 4 5; do
    f="$IN/keys-$w/key-$i.xpub"
    fp=$(sed -n 's/.*origin \[\([0-9a-f]*\)\/.*/\1/p' "$f" | head -1)
    pa=$(sed -n 's/.*origin \[[0-9a-f]*\/\([^]]*\)\].*/\1/p' "$f" | head -1)
    xp=$(grep '^xpub' "$f" | head -1)
    KEYARGS+=(--key "@$i=$xp"); FPARGS+=(--fingerprint "@$i=$fp")
    printf '[%s/%s]%s\n' "$fp" "$pa" "$xp" >> "$KEYFILE"
  done

  echo "############################################################"
  echo "########## $w"
  echo "############################################################"
  echo

  echo "=== 5$w. The md1 KEYLESS template ==="
  echo
  echo "Fingerprints are declared (F-227): all six slots share one origin path,"
  echo "so without them a gathered key card matches every slot and seating must"
  echo "refuse the whole set."
  echo
  runcap "$O/md1-template.txt" '^md1' \
    "$MD" encode "$P" --group-size 0 --experimental "${FPARGS[@]}"
  mapfile -t TMPL < "$O/md1-template.txt"
  echo "The keyless template is ${#TMPL[@]} md1 chunk(s)."
  echo
  run "$MD" verify --template "$P" "${FPARGS[@]}" "${TMPL[@]}" --experimental
  if ! "$MD" verify --template "$P" "${FPARGS[@]}" "${TMPL[@]}" --experimental >/dev/null 2>&1; then
    fatal "$w: the keyless card set does not re-encode to its own policy"
  fi
  run "$MD" inspect "${TMPL[@]}"

  echo "=== 6$w. The md1 KEYED concrete wallet descriptor ==="
  echo
  runcap "$O/md1-keyed.txt" '^md1' \
    "$MD" encode "$P" "${KEYARGS[@]}" "${FPARGS[@]}" --group-size 0 --experimental
  mapfile -t KEYED < "$O/md1-keyed.txt"
  echo "The keyed card set is ${#KEYED[@]} md1 chunk(s)."
  echo

  TID=$("$MD" inspect "${TMPL[@]}" 2>/dev/null | sed -n 's/^wallet-descriptor-template-id: //p')
  TIDK=$("$MD" inspect "${KEYED[@]}" 2>/dev/null | sed -n 's/^wallet-descriptor-template-id: //p')
  PID=$("$MD" inspect "${KEYED[@]}" 2>/dev/null | sed -n 's/^wallet-policy-id: //p')
  echo "  wallet-descriptor-template-id (keyless): $TID"
  echo "  wallet-descriptor-template-id (keyed)  : $TIDK"
  echo "  wallet-policy-id              (keyed)  : $PID"
  [ -n "$TID" ] && [ "$TID" = "$TIDK" ] || \
    fatal "$w: the template id differs between the keyless and keyed forms"
  echo
  echo "ONE WALLET, TWO IDS. The template id is key-STABLE and identical either"
  echo "way; the policy id depends on the keys. A card binds to whichever of the"
  echo "two matches its own form."
  echo

  echo "=== 7$w. The concrete descriptor ==="
  echo
  runcap "$O/descriptor.txt" '.' "$MD" descriptor "${KEYED[@]}"
  echo "  $(wc -c < "$O/descriptor.txt") bytes"
  echo

  echo "=== 8$w. First 5 addresses, both chains, ON THE HOST ==="
  echo
  for ch in 0 1; do
    label=$([ "$ch" = 0 ] && echo receive || echo change)
    runcap "$O/$label.txt" '^bc1' "$MD" address "${KEYED[@]}" --chain "$ch" --count 5
    n=$(grep -c '^bc1' "$O/$label.txt" 2>/dev/null || echo 0)
    [ "$n" -eq 5 ] || fatal "$w: expected 5 $label addresses, got $n"
  done

  echo "=== 9$w. The mk1 key cards, bound to the TEMPLATE id ==="
  echo
  run cat "$KEYFILE"
  FROM_MD1=(); for c in "${TMPL[@]}"; do FROM_MD1+=(--from-md1 "$c"); done
  if ! "$MK" encode --keys "$KEYFILE" "${FROM_MD1[@]}" --json > "$O/mk-encode.json" 2>"$O/mk.err"; then
    cat "$O/mk.err"; fatal "$w: mk encode --keys failed"
  fi
  cat "$O/mk.err"; rm -f "$O/mk.err"
  run "$W/mk_cards_from_json.py" "$O/mk-encode.json" "$O/mk-encode-raw.txt"

  # The stub the cards actually embed must be the TEMPLATE id's prefix, not the
  # policy id's -- that is what makes them seat onto the keyless template.
  TID8=$(printf '%s' "$TID" | cut -c1-8)
  NCH=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["cards"][0]["chunk_count"])' "$O/mk-encode.json")
  STUB=$("$MK" decode $(head -n "$NCH" "$O/mk-encode-raw.txt" | tr '\n' ' ') 2>/dev/null | sed -n 's/^policy_id_stubs: *//p' | head -1)
  echo "template-id prefix: $TID8   stub the cards embed: $STUB"
  [ "$STUB" = "$TID8" ] || fatal "$w: the key cards bind to $STUB, not the template id $TID8"
  echo

  echo "=== 10$w. me bundle: the plate checklist ==="
  echo
  cat "$O/md1-template.txt" "$O/mk-encode-raw.txt" > "$O/backup-strings.txt"
  echo "The engraved set: $(grep -c '^md1' "$O/backup-strings.txt") md1 + $(grep -c '^mk1' "$O/backup-strings.txt") mk1 = $(grep -c . "$O/backup-strings.txt") public strings."
  echo
  rm -rf "$O/plates" && mkdir -p "$O/plates"
  run "$ME" bundle --in "$O/backup-strings.txt" --preview "$O/plates" --png --manifest "$O/manifest.json"
done

echo "############################################################"
echo "########## both wrappers"
echo "############################################################"
echo

echo "=== 11. tr and wsh are DIFFERENT WALLETS ==="
echo
echo "  wrapper  template-id                       first receive address"
for w in tr wsh; do
  O="$OUT/$w"
  t=$("$MD" inspect $(tr '\n' ' ' < "$O/md1-template.txt") 2>/dev/null | sed -n 's/^wallet-descriptor-template-id: //p')
  a=$(head -1 "$O/receive.txt")
  printf '  %-7s  %s  %s\n' "$w" "$t" "$a"
done
echo
TT=$("$MD" inspect $(tr '\n' ' ' < "$OUT/tr/md1-template.txt") 2>/dev/null | sed -n 's/^wallet-descriptor-template-id: //p')
TW=$("$MD" inspect $(tr '\n' ' ' < "$OUT/wsh/md1-template.txt") 2>/dev/null | sed -n 's/^wallet-descriptor-template-id: //p')
[ "$TT" != "$TW" ] || fatal "tr and wsh produced the SAME template id -- they must not"
if diff -q <(sort "$OUT/tr/receive.txt") <(sort "$OUT/wsh/receive.txt") >/dev/null 2>&1; then
  fatal "tr and wsh produced the same addresses -- they must not"
fi
echo "Different ids, different addresses, as they must be."
echo

echo "=== 12. The payload route: bundle -> systemwide payload, NO ms1 ==="
echo
cat <<'TXT'
`me sysw pack` builds the SYSTEMWIDE container the device reads. This journey's
wallet carries no ms1 secret share -- the three preimages are engraved as text,
not as ms1 -- so the payload holds only public strings.
TXT
echo
cat "$OUT/tr/backup-strings.txt" "$OUT/wsh/backup-strings.txt" > "$OUT/payload-strings.txt"
NMS1=$(grep -c '^ms1' "$OUT/payload-strings.txt" || true)
echo "Strings for the payload: $(grep -c . "$OUT/payload-strings.txt") total, ms1 count = $NMS1"
[ "$NMS1" -eq 0 ] || fatal "ms1 strings present in a payload that must carry none"
echo
runcap "$OUT/payload-pack.txt" '.' \
  "$ME" sysw pack --in "$OUT/payload-strings.txt" --out "$OUT/payload.bin" --no-passphrase
[ -s "$OUT/payload.bin" ] || fatal "sysw pack produced no payload"
echo "Payload: $(wc -c < "$OUT/payload.bin") bytes."
echo
run "$ME" sysw show "$OUT/payload.bin"

# The container must hold every public string from BOTH wrappers and no more.
NREC=$("$ME" sysw show "$OUT/payload.bin" 2>/dev/null | grep -c '^public record ')
NWANT=$(grep -c . "$OUT/payload-strings.txt")
echo "public records in the container: $NREC   strings fed in: $NWANT"
[ "$NREC" -eq "$NWANT" ] || fatal "payload holds $NREC records, fed $NWANT"
if "$ME" sysw show "$OUT/payload.bin" 2>/dev/null | grep -q 'sealed: *true'; then
  fatal "this route must produce an UNSEALED container; section 13 is the sealed one"
fi
echo

echo "=== 13. The sealed-payload route ==="
echo
cat <<'TXT'
`me seal` encrypts the records and emits a UF2 for `picotool load`. The
passphrase is GENERATED, never supplied -- a memorable one does not survive an
offline attack on a stolen machine.

IT IS SEALED PER WRAPPER, AND NOT BY CHOICE. `me seal` accepts 1..=24 records;
the two bundles together are 46, so the combined set is REFUSED. Each wrapper's
23 strings fit with one to spare. That is a real limit of this route and the
unsealed `sysw pack` above does not share it -- it took all 46.
TXT
echo
run "$ME" seal --in "$OUT/payload-strings.txt" --out "$OUT/sealed-both.uf2" --iterations 100000
if [ -s "$OUT/sealed-both.uf2" ]; then
  fatal "sealing all 46 records SUCCEEDED -- the 24-record cap this section documents is gone, rewrite it"
fi
echo "Refused, as documented. Now per wrapper:"
echo
for w in tr wsh; do
  n=$(grep -c . "$OUT/$w/backup-strings.txt")
  echo "-- $w: $n records"
  runcap "$OUT/$w/seal.txt" '.' \
    "$ME" seal --in "$OUT/$w/backup-strings.txt" --out "$OUT/$w/sealed.uf2" --iterations 100000
  [ -s "$OUT/$w/sealed.uf2" ] || fatal "$w: seal produced no UF2"
  echo "   sealed UF2: $(wc -c < "$OUT/$w/sealed.uf2") bytes"
  echo
done

echo "=== 14. Wallet files: what this wallet can and cannot export ==="
echo
cat <<'TXT'
`mnemonic export-wallet` (mnemonic-toolkit, shipped since v0.97.0) emits 11
formats. Run against BOTH concrete descriptors, every format, nothing hidden:
TXT
echo
TK=/scratch/code/shibboleth/mnemonic-toolkit/target/debug/mnemonic
EXP="$OUT/exports"; rm -rf "$EXP"; mkdir -p "$EXP"
printf '  %-5s %-14s %-12s %s\n' wrap format result detail
NEMIT=0
for w in tr wsh; do
  D=$(cat "$OUT/$w/descriptor.txt")
  for f in descriptor bsms bip388 bitcoin-core sparrow electrum specter jade coldcard; do
    if "$TK" export-wallet --descriptor "$D" --format "$f" > "$EXP/rcw-$w.$f.txt" 2>"$EXP/e"; then
      printf '  %-5s %-14s %-12s %s bytes\n' "$w" "$f" EMITTED "$(wc -c < "$EXP/rcw-$w.$f.txt")"
      NEMIT=$((NEMIT+1))
    else
      rc=$?; rm -f "$EXP/rcw-$w.$f.txt"
      printf '  %-5s %-14s refused(%d)  %s\n' "$w" "$f" "$rc" "$(tail -1 "$EXP/e" | cut -c1-58)"
    fi
  done
done
rm -f "$EXP/e"
echo
echo "$NEMIT of 18 (wrapper x format) combinations emitted a file."
echo
cat <<'TXT'
THE TAPROOT FORM EMITS NOTHING, and every format fails at the SAME place --
"All spend paths must require a signature", before format selection is even
reached. That is rust-miniscript's sanity_check() refusing tier 4, which needs
no key. `md encode` has --experimental for exactly this; export-wallet has no
equivalent (filed as G1 in design/PLAN_wallet_file_export.md).

AND IT WOULD NOT HELP THE OPERATOR IF IT DID. Measured against a real Bitcoin
Core 25 node: Core refuses the keyless tier 4 too, and accepts the identical
script once tier 4 has a key. Nunchuk refuses through the same check
(libnunchuk's IsSane/NeedsSignature). Sparrow refuses for a different reason --
it has no miniscript engine at all. Relaxing OUR gate would emit a file no
target will import.
TXT
echo

echo "=== 15. Three implementations, one address ==="
echo
# The BSMS record's 4th line is BIP-129's canary: the wallet's first address, as
# computed by the EMITTER. Compare it against md's own derivation and against
# what SeedHammer II showed when it seated six key cards onto the template.
BSMS_ADDR=$(sed -n '4p' "$EXP/rcw-wsh.bsms.txt" 2>/dev/null)
HOST_ADDR=$(head -1 "$OUT/wsh/receive.txt")
DEV_JSON="$W/shots/rcw-wsh-seating-result.json"
if [ -f "$DEV_JSON" ]; then
  DEV_ADDR=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['matched']['addresses'][0])" "$DEV_JSON")
else
  DEV_ADDR="(no device walk captured — run capture_rcw.py --wrapper wsh --route seating)"
fi
echo "  BSMS canary (mnemonic-toolkit emitter) : $BSMS_ADDR"
echo "  md address  (descriptor-mnemonic)      : $HOST_ADDR"
echo "  SeedHammer II (Go, over NFC, seated)   : $DEV_ADDR"
echo
if [ -n "$BSMS_ADDR" ] && [ "$BSMS_ADDR" = "$HOST_ADDR" ] && [ "$HOST_ADDR" = "$DEV_ADDR" ]; then
  echo "ALL THREE AGREE — three implementations, two languages, one air gap."
else
  fatal "the BSMS canary, md and the device do not agree on the first address"
fi
echo

echo "=== Artifacts ==="
run ls -la "$OUT"

if [ "$FATAL" -ne 0 ]; then
  echo "TRANSCRIPT FAILED: at least one gate is red (see FATAL above)."
  exit 1
fi
echo "All gates green."
