#!/usr/bin/env python3
"""Generate the S0 Structured Append test fixture — and the ORACLE P5 must match.

WHY THIS EXISTS, and why it is deliberately NOT our encoder
-----------------------------------------------------------
`SPEC_engrave_transaction.md` §4.2c separates two questions that were tangled:

  physics   can a scanner read Structured Append off engraved steel?
            -> S0, FIRST, from THIS generator
  software  does OUR encoder emit it correctly?
            -> P5, whose gate must reproduce this fixture MODULE-FOR-MODULE

The obvious objection is that the thing tested is not the thing shipped. That is
the point: because P5 must reproduce this output exactly, **this file is a
cross-implementation oracle** — an independent encoder's output ours must match.
Testing our encoder against itself is the shape a prior cycle's pinned corpus had
when it turned out to be uniformly wrong.

The fork's vendored QR library (`github.com/seedhammer/kortschak-qr v0.3.2`) has
NO Structured Append at all — verified: zero occurrences, `Encode` returns one
`*Code`. So there is nothing in-tree that could have produced this, which is what
makes the independence real rather than nominal.

WHAT IT PINS
------------
Per symbol: version, ECC level, **mask**, index, count, and the full module
matrix. The mask is per-symbol — the encoder chooses it by penalty scoring, and
this generator emits symbols with DIFFERENT masks in one set. A gate that pins
one mask for the whole sequence would be wrong.

RUN
---
    python3 -m venv .venv && .venv/bin/pip install segno
    .venv/bin/python scripts/gen-sa-fixture.py > design/measurements/SA_FIXTURE.txt
"""
import sys

try:
    import segno
except ImportError:
    sys.exit("gen-sa-fixture: needs `segno` (pip install segno). It is deliberately\n"
             "NOT the fork's QR library: this fixture's value is being independent of\n"
             "the encoder P5 will write.")

# A FIXED payload, so the fixture is reproducible byte-for-byte. Not a real
# transaction: this plate tests whether Structured Append SCANS off steel, and a
# bearer transaction on a test plate is a hazard with no upside.
PAYLOAD = b"SEEDHAMMER-SA-FIXTURE-2026-08-24-" + bytes(range(0, 96))
SYMBOLS = 2          # §4.2c says "a Structured-Append pair"
ERROR = "m"          # the ruled floor (§4.5b). segno may upgrade if there is room.


def main() -> int:
    seq = segno.make_sequence(PAYLOAD, symbol_count=SYMBOLS, error=ERROR)

    print("SEEDHAMMER S0 — QR STRUCTURED APPEND FIXTURE")
    print("generated by scripts/gen-sa-fixture.py using segno", segno.__version__)
    print()
    print(f"payload      : {len(PAYLOAD)} bytes, fixed (see the script)")
    print(f"payload sha  : {__import__('hashlib').sha256(PAYLOAD).hexdigest()}")
    print(f"symbols      : {len(seq)}")
    print()
    print("THE MASK IS PER SYMBOL. A gate pinning one mask for the sequence is wrong.")
    print()

    for i, q in enumerate(seq):
        size = q.symbol_size(border=0)[0]
        print(f"--- symbol {i + 1} of {len(seq)} ---")
        print(f"  version   : {q.version}")
        print(f"  ecc       : {q.error}")
        print(f"  mask      : {q.mask}")
        print(f"  designator: {q.designator}")
        print(f"  modules   : {size} x {size}")
        print("  matrix    : (1 = dark, 0 = light; no quiet zone)")
        for row in q.matrix:
            print("    " + "".join("1" if m else "0" for m in row))
        print()

    print("=== WHAT P5's GATE MUST REPRODUCE ===")
    print("For each symbol, byte-for-byte: version, ecc, mask, and every matrix row.")
    print("coding.NewPlan(version, level, mask) takes the mask explicitly, so this is")
    print("a byte comparison and not a judgement call.")
    print()
    print("=== WHAT THIS FIXTURE DOES *NOT* ESTABLISH ===")
    print("It is ENCODE-ONLY. segno does not decode, so nothing here proves these")
    print("symbols reassemble -- that is exactly what S0's scan answers, off steel,")
    print("with a real scanner. A green run of this script is not a green gate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
